FROM python:3.11.6-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir /app/scheduler

# Copy requirements and install dependencies
COPY backend/scheduler/requirements.txt ./scheduler/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r scheduler/requirements.txt

COPY backend/core ./core
RUN pip install -e ./core

# Copy the source code
COPY backend/scheduler ./scheduler
